spring:
  application:
    name: cloud-zuul

server:
  port: 8763

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  ignored-services: "*"
  strip-prefix: true
  routes:
    app-console-web:
      path: /console/**
      serviceId: app-console-web